service: samanrio-cloud-week
frameworkVersion: '2 || 3'

custom:
  subjectTableName: 'subject-gov-table-${sls:stage}'
  

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ SubjectTable, Arn ]
  environment:
    SUBJECT_TABLE: ${self:custom.subjectTableName}

functions:
  # api:
  #   handler: handler.handler
  #   events:
  #     - httpApi: '*'
      # - http: 
      #   cors: true
  get:
    handler: getSubjectData.getSubjectData
    events:
      - http:
          path: /{title}
          method: get
          cors: true
  post:
    handler: postSubjectData.saveSubjectData
    events:
      - http:
          path: /{title}
          method: post
          cors: true

resources:
  Resources:
    SubjectTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.subjectTableName}
